const fs=require('fs'),path=require('path');const {chromium}=require('playwright');const assert=require('assert');const root=path.resolve(__dirname,'..'),base=process.env.BMAI_BASE_URL||'http://127.0.0.1:8765/';
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);const pages=walk(root).filter(p=>p.endsWith('.html')&&!/(^|[\\/])(qa|templates|node_modules|test-results|dist)[\\/]/.test(path.relative(root,p))&&!p.endsWith('hero-approval.html')).map(p=>path.relative(root,p).replaceAll('\\','/'));
(async()=>{const browser=await chromium.launch({...(process.platform==='win32'?{channel:'chrome'}:{}),headless:true});const results=[];fs.mkdirSync(path.join(root,'qa/artifacts/cohesion'),{recursive:true});
for(const width of [390,820,1440]){const context=await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce'});const p=await context.newPage();await p.clock.install({time:new Date('2026-11-23T12:00:00+05:30')});const failures=[];p.on('pageerror',e=>failures.push(e.message));p.on('response',r=>{if(r.url().startsWith(base)&&r.status()>=400)failures.push(r.status()+' '+r.url())});
for(const file of pages){const start=Date.now();await p.goto(new URL(file,base).href,{waitUntil:'load'});for(const avatar of await p.locator('.studio-avatar').all()){if(!await avatar.isVisible())continue;await avatar.scrollIntoViewIfNeeded();await p.waitForTimeout(100);}await p.waitForTimeout(300);await p.evaluate(async()=>{await Promise.all([...document.images].map(img=>img.decode().catch(()=>{})))});const result=await p.evaluate(()=>{const main=document.querySelector('main');return{overflow:document.documentElement.scrollWidth-innerWidth,header:!!document.querySelector('.bmai-global-header .bmai-session-brand'),home:!!document.querySelector('.bmai-header-home'),main:!!main,skip:!!document.querySelector('.bmai-skip-link'),css:[...document.styleSheets].filter(x=>x.href?.includes('components.css')).length,broken:[...document.images].filter(i=>!i.naturalWidth).map(i=>i.src),links:[...document.querySelectorAll('a[href]')].map(a=>a.href).filter(x=>x.startsWith(location.origin)),avatars:[...document.querySelectorAll('.studio-avatar')].filter(e=>e.getBoundingClientRect().width&&e.getBoundingClientRect().height).map(e=>({pose:e.className,bg:getComputedStyle(e).backgroundImage,w:e.clientWidth,h:e.clientHeight})),nav:performance.getEntriesByType('navigation')[0]?.toJSON(),transfer:performance.getEntriesByType('resource').filter(r=>r.name.startsWith(location.origin)).reduce((s,r)=>s+r.transferSize,0)}});
assert(result.overflow<=1,file+' overflow '+width);assert(result.header&&result.home&&result.main&&result.skip,file+' missing shell');assert.equal(result.css,1,file+' missing shared CSS');assert.equal(result.broken.length,0,file+' broken images');for(const a of result.avatars){assert.notEqual(a.bg,'none',file+' missing avatar '+a.pose);assert(Math.abs(a.w-a.h)<=1,file+' distorted avatar');}
for(const url of new Set(result.links)){const u=new URL(url),rel=decodeURIComponent(u.pathname).replace(/^\//,'');const local=path.join(root,rel||'index.html');assert(fs.existsSync(local),file+' broken link '+url);if(u.hash&&u.pathname===new URL(file,base).pathname){assert(await p.evaluate(hash=>!!document.getElementById(decodeURIComponent(hash.slice(1))),u.hash),file+' missing anchor '+u.hash);}}
if(width!==820)await p.screenshot({path:path.join(root,'qa/artifacts/cohesion',file.replaceAll('/','-')+'-'+width+'.png'),fullPage:true,animations:'disabled'});results.push({file,width,loadMs:Date.now()-start,domReadyMs:Math.round((result.nav?.domContentLoadedEventEnd||0)),localTransferBytes:result.transfer,avatarCount:result.avatars.length});console.log(width,file,'passed');}
assert.equal(failures.length,0,failures.join(';'));await context.close();}
await browser.close();fs.writeFileSync(path.join(root,'qa/cohesion-results.json'),JSON.stringify({createdAt:new Date().toISOString(),base,results},null,2));console.log('All '+results.length+' page/viewport combinations passed.');})().catch(e=>{console.error(e);process.exit(1)});
