const {chromium}=require('playwright'),assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const base=process.env.BMAI_BASE_URL||'http://127.0.0.1:8766/';
const schedule=vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../library/schedule.js'),'utf8')+';window.BMAI_SESSIONS',{window:{}});
(async()=>{const browser=await chromium.launch({...(process.platform==='win32'?{channel:'chrome'}:{}),headless:true});try{
 const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const first=schedule[0],second=schedule[1];await page.clock.install({time:new Date(Date.parse(second.start)-2000)});await page.clock.pauseAt(new Date(Date.parse(second.start)-2000));await page.goto(new URL('index.html',base).href);
 assert.equal(await page.locator('#bmaiSchedule .schedule-row').count(),schedule.length);assert.equal(await page.locator('.bmai-week').count(),new Set(schedule.map(s=>s.id.match(/week-(\d+)/)[1])).size);
 for(const section of ['playbooks','homework']){assert.equal(await page.locator('#'+section+' article.card').count(),1);assert.equal(await page.locator('#'+section+' select option').count(),schedule.length);}
 assert(await page.locator('a[data-bmai-lock-guard]').count()>0);await page.clock.runFor(2500);assert((await page.locator('.bmai-studio-card h2').textContent()).includes(second.title));
 let routes=0;
 for(const session of schedule){for(const route of [session.session,session.playbook,session.promptbook].filter(Boolean)){const promptVault=route===session.promptbook;await page.clock.setSystemTime(new Date(Date.parse(session.start)-1000));await page.goto(new URL(route,base).href);if(promptVault){const group=page.locator(`[data-vault-session="${session.id}"]`);assert.equal(await page.locator('.bmai-lock-screen').count(),0,route+' should keep the shared Vault open');assert.equal(await group.locator('[data-vault-locked]:visible').count(),1,route+' exposes prompts early');assert.equal(await group.locator('.prompt-vault-card:visible').count(),0,route+' exposes prompt text early');}else{assert.equal(await page.locator('.bmai-lock-screen').count(),1,route+' opens early');for(const a of await page.locator('.bmai-session-top-actions a[href*="docs.google.com"]').all())assert.equal(await a.getAttribute('aria-disabled'),'true');}await page.clock.setSystemTime(new Date(session.start));await page.goto(new URL(route,base).href);if(promptVault){const group=page.locator(`[data-vault-session="${session.id}"]`);assert.equal(await group.locator('[data-vault-locked]:visible').count(),0,route+' remains locked');assert(await group.locator('.prompt-vault-card:visible').count()>0,route+' did not reveal released prompts');}else assert.equal(await page.locator('.bmai-lock-screen').count(),0,route+' remains locked');routes++;}}
 await page.clock.setSystemTime(new Date(Date.parse(second.start)-2000));await page.goto(new URL(second.playbook,base).href);const before=await page.locator('#bmaiLockCount').textContent();await page.clock.runFor(1100);assert.notEqual(await page.locator('#bmaiLockCount').textContent(),before);await page.clock.runFor(1200);await page.waitForFunction(()=>!document.querySelector('.bmai-lock-screen'));
 await page.clock.setSystemTime(new Date(first.start));await page.goto(new URL('index.html',base).href);await page.locator('#homework select').selectOption(second.id);assert((await page.locator('#homework .bmai-availability').textContent()).includes('Locked'));const link=page.locator('#homework article a');assert.equal(await link.getAttribute('aria-disabled'),'true');await link.click({force:true});await page.waitForURL('**/'+second.session);assert.equal(await page.locator('.bmai-lock-screen').count(),1);assert.equal(errors.length,0,errors.join('; '));
 console.log('Release boundaries passed for '+routes+' authored routes; hub updates, countdowns, auto-unlock and homework guards passed.');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exit(1)});
