const{chromium}=require('playwright');const assert=require('assert');const base=process.env.BMAI_BASE_URL||'http://127.0.0.1:8765/';
(async()=>{const b=await chromium.launch({...(process.platform==='win32'?{channel:'chrome'}:{}),headless:true});const p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.install({time:new Date('2026-10-10T19:59:58+05:30')});await p.goto(new URL('index.html',base).href);if(await p.evaluate(()=>window.BMAI_LOCKS_PAUSED_FOR_REVIEW)){
 assert.equal(await p.locator('#bmaiSchedule .schedule-row').count(),7,'all authored sessions should appear on the homepage');
 assert.equal(await p.locator('#playbooks article.card').count(),7,'all playbooks should appear on the homepage');
 assert.equal(await p.locator('#homework article.card').count(),7,'all homework documents should appear on the homepage');
 assert(await p.locator('#bmaiReviewBanner').isVisible(),'review access notice should be visible');
 assert.equal(await p.locator('.studio-resource-locked').count(),0,'resource cards should open for review');
 assert.equal(await p.locator('a[data-bmai-lock-guard]').count(),0,'review links should stay open');
 for(const route of ['sessions/week-3-day-2/index.html','sessions/week-3-day-2/playbook.html','sessions/week-4-day-1/index.html','sessions/week-4-day-1/playbook.html','sessions/week-4-day-2/index.html','sessions/week-4-day-2/playbook.html']){
  await p.goto(new URL(route,base).href);
  assert.equal(await p.locator('.bmai-lock-screen').count(),0,route+' should open for review');
  assert.equal(await p.locator('main#main-content').count(),1,route+' should retain the main landmark');
  if(route.endsWith('playbook.html'))assert(await p.locator('[data-library-quiz] fieldset').count()>0,route+' practice should open');
 }
 assert.equal(errors.length,0,errors.join(';'));
 console.log('Review access, homepage libraries, resources, and six lesson pages passed');
 await b.close();return;
}await p.locator('#bmaiUpcomingSessions>summary').click();assert((await p.locator('#bmaiUpcomingList .countdown').count())>=3,'upcoming list should include the scheduled sessions');assert(await p.locator('a[data-bmai-lock-guard]').count()>0);await p.clock.runFor(2500);assert((await p.locator('.bmai-studio-card h2').textContent()).includes('Build Your First'));await p.goto(new URL('sessions/week-2-day-1/index.html',base).href);assert.equal(await p.locator('.bmai-lock-screen').count(),0);
await p.clock.setSystemTime(new Date('2026-10-11T19:59:58+05:30'));await p.goto(new URL('sessions/week-2-day-2/playbook.html',base).href);assert.equal(await p.locator('.bmai-lock-screen').count(),1);const before=await p.locator('#bmaiLockCount').textContent();await p.clock.runFor(1100);assert.notEqual(await p.locator('#bmaiLockCount').textContent(),before);await p.clock.runFor(1200);await p.waitForLoadState('load');assert.equal(await p.locator('.bmai-lock-screen').count(),0);
await p.clock.setSystemTime(new Date('2026-10-05T20:00:00+05:30'));await p.goto(new URL('index.html',base).href);const doc=p.locator('#homework a[href*="1zdEzg"]');assert.equal(await doc.getAttribute('aria-disabled'),'true');await doc.click({force:true});await p.waitForURL('**/sessions/week-2-day-1/index.html');assert.equal(await p.locator('.bmai-lock-screen').count(),1);for(const route of ['sessions/week-2-day-1/playbook.html','sessions/week-2-day-2/index.html','sessions/week-2-day-2/homework.html','sessions/week-3-day-1/index.html','sessions/week-3-day-1/playbook.html']){await p.goto(new URL(route,base).href);assert.equal(await p.locator('.bmai-lock-screen').count(),1,route);const homework=p.locator('.bmai-session-top-actions a[href*="docs.google.com"]');if(await homework.count())assert.equal(await homework.first().getAttribute('aria-disabled'),'true',route+' header homework guard');}for(const [route,release] of [['sessions/week-3-day-2/index.html','2026-10-18T20:00:00+05:30'],['sessions/week-4-day-1/playbook.html','2026-10-24T20:00:00+05:30'],['sessions/week-4-day-2/index.html','2026-10-25T20:00:00+05:30']]){await p.clock.setSystemTime(new Date(new Date(release).getTime()-1000));await p.goto(new URL(route,base).href);assert.equal(await p.locator('.bmai-lock-screen').count(),1,route+' must remain locked before release');await p.clock.setSystemTime(new Date(release));await p.goto(new URL(route,base).href);assert.equal(await p.locator('.bmai-lock-screen').count(),0,route+' should unlock at release');}assert.equal(errors.length,0,errors.join(';'));console.log('Local locks, countdown ticks, boundary auto-unlock, and external homework guard passed');await b.close();})().catch(e=>{console.error(e);process.exit(1)});

