const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert'),{execFileSync}=require('child_process'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),base=process.env.BMAI_BASE_URL||'http://127.0.0.1:8778/';
const out=path.join(__dirname,'artifacts/audit-fixes');fs.mkdirSync(out,{recursive:true});
const schedule=vm.runInNewContext(fs.readFileSync(path.join(root,'library/schedule.js'),'utf8')+';window.BMAI_SESSIONS',{window:{}});
const manifest=JSON.parse(fs.readFileSync(path.join(root,'content/prompt-vault-manifest.json'),'utf8'));
const oldManifest=JSON.parse(execFileSync('git',['show','HEAD:content/prompt-vault-manifest.json'],{cwd:root,encoding:'utf8'}));
for(const old of oldManifest.filter(item=>item.kind==='official')){const item=manifest.find(item=>item.id===old.id);assert(item,'Lost official deep link '+old.id);assert.equal(item.text.replace(/\r\n/g,'\n'),old.text.replace(/\r\n/g,'\n'),'Changed official text '+old.id);}
const pre=html=>[...html.matchAll(/<pre\b[^>]*>([\s\S]*?)<\/pre>/g)].map(m=>m[1].replace(/\r\n/g,'\n'));
for(const session of schedule)for(const route of [session.session,session.playbook])assert.deepEqual(pre(fs.readFileSync(path.join(root,route),'utf8')),pre(execFileSync('git',['show','HEAD:'+route],{cwd:root,encoding:'utf8'})),route+' changed a source prompt');
const results={checks:['Official text and deep links preserved'],screenshots:[]};
(async()=>{const browser=await chromium.launch({...(process.platform==='win32'?{channel:'chrome'}:{}),headless:true});try{
 const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce',permissions:['clipboard-read','clipboard-write'],acceptDownloads:true});
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.install({time:new Date('2026-10-09T12:00:00+05:30')});
 await page.goto(base+'prompt-vault.html?session=week-1-day-2');
 const first=page.locator('#prompt-vault-week-1-day-2-01-keep-the-spoken-story-natural'),second=page.locator('#prompt-vault-week-1-day-2-02-keep-the-spoken-story-natural');
 assert((await first.locator('h3').textContent()).includes('channel research'));assert((await second.locator('h3').textContent()).includes('JSON'));
 assert.equal(await first.locator('[data-prompt-field]').count(),6);assert.equal(await second.locator('[data-prompt-field]').count(),1);
 assert.equal(await second.locator('[data-prompt-field]').getAttribute('data-prompt-field'),'[character action]');
 const values=['mystery stories','new filmmakers','English','Night Studio','a small budget','2026-12-01'];for(const [i,input]of (await first.locator('[data-prompt-field]').all()).entries())await input.fill(values[i]);
 await first.locator('[data-prompt-copy]').click();const working=(await page.evaluate(()=>navigator.clipboard.readText())).replace(/\r\n/g,'\n');assert(!/\{[A-Z_]+\}/.test(working));assert(working.includes('Night Studio'));
 await first.locator('[data-prompt-original]').click();
 // Original clipboard identity is compared independently of all substitutions.
 const original=manifest.find(item=>item.id==='prompt-vault-week-1-day-2-01-keep-the-spoken-story-natural').text;assert.equal((await page.evaluate(()=>navigator.clipboard.readText())).replace(/\r\n/g,'\n'),original.replace(/\r\n/g,'\n'));
 const action='hero says "hello"\nthen walks';await second.locator('[data-prompt-field]').fill(action);const jsonText=await second.locator('pre').textContent();const parsed=JSON.parse(jsonText.split('OUTPUT FORMAT (JSON):')[1].trim());assert(parsed[0].visual_prompt.includes(action));
 await second.locator('[data-prompt-copy]').click();assert.equal((await page.evaluate(()=>navigator.clipboard.readText())).replace(/\r\n/g,'\n'),jsonText);
 await second.locator('[data-prompt-reset]').click();assert.equal(await second.locator('pre').textContent(),manifest.find(item=>item.id==='prompt-vault-week-1-day-2-02-keep-the-spoken-story-natural').text);
 await second.locator('[data-prompt-copy]').click();assert((await second.locator('[data-prompt-field-status]').textContent()).includes('1 field'));assert(await second.locator('[data-prompt-field]').evaluate(e=>e===document.activeElement));
 assert(await first.locator('.prompt-vault-source a').count());results.checks.push('Safe JSON substitutions, six named research fields, original copying, reset and missing-field feedback');
 const tab=page.locator('[data-vault-session-button="week-1-day-2"]');await tab.focus();await tab.press('ArrowRight');assert.equal(await page.locator('[data-vault-session-button="week-2-day-1"]').getAttribute('aria-selected'),'true');
 assert.equal(await page.locator('#vault-results').getAttribute('aria-labelledby'),'vault-tab-week-2-day-1');assert.equal(await page.locator('[data-vault-session="week-2-day-1"] .prompt-vault-card:visible').count(),0);
 await page.locator('[aria-selected="true"][data-vault-session-button]').press('End');assert.equal(await page.locator('[data-vault-session-button="week-8-day-2"]').getAttribute('aria-selected'),'true');await page.locator('[aria-selected="true"][data-vault-session-button]').press('Home');assert.equal(await page.locator('[data-vault-session-button=""]').getAttribute('aria-selected'),'true');results.checks.push('Vault arrow, Home/End, focus, panel associations and scheduled prompt locks');
 await page.goto(base);await page.locator('#bmai-site-search').fill('First AI Movie');assert.equal(await page.locator('[data-site-search-results] a').count(),0);
 await page.locator('[data-site-search-availability]').selectOption('all');const homework=page.locator('[data-site-search-results] a').filter({hasText:'Assignment and submission instructions'}).first();assert((await homework.getAttribute('href')).endsWith('/sessions/week-2-day-1/playbook.html#share'));assert.equal(await homework.getAttribute('aria-disabled'),'true');assert((await homework.textContent()).includes('Locked'));
 assert.equal(await page.locator('[data-site-search-results] a[href*="docs.google.com"]').count(),0);await homework.click({force:true});assert.equal(await page.locator('.bmai-lock-screen').count(),1);
 await page.goto(base);await page.locator('#bmai-site-search').fill('YouTube');assert.equal(await page.locator('[data-site-search-results] a[href*="week-5"]').count(),0);results.checks.push('Search availability, dynamic lock guards, exact homework handoff and hidden-future filtering');
 await page.locator('#catch-up summary').click();assert.equal(await page.locator('[aria-label="Choose a catch-up lesson"] option').count(),1);assert.equal(await page.locator('#catch-up a[href*="docs.google.com"]').count(),0);
 await page.clock.setSystemTime(new Date('2026-11-23T12:00:00+05:30'));await page.goto(base);await page.locator('#catch-up summary').click();assert.equal(await page.locator('[aria-label="Choose a catch-up lesson"] option').count(),15);
 for(const session of schedule){await page.goto(base+session.session);await page.locator('#catch-up summary').click();const links=await page.locator('#catch-up ol a').evaluateAll(es=>es.map(e=>e.href));assert(links.length);for(const href of links){const u=new URL(href);assert.equal(u.pathname,new URL(session.session,base).pathname);assert(await page.locator(u.hash).count(),href+' missing target');}assert.equal(await page.locator('#catch-up a[href*="docs.google.com"]').count(),0);}
 results.checks.push('All 15 source-linked catch-up routes and canonical playbook handoffs');
 await page.setViewportSize({width:320,height:844});
 for(const session of schedule){await page.goto(base+session.playbook);await page.locator('#share .bmai-handoff details summary').click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),session.id+' homework help overflows');assert((await page.locator('#share .bmai-handoff').textContent()).includes('existing cohort support'));}
 results.checks.push('Homework-access troubleshooting opens on all playbooks at 320 pixels');
 await page.goto(base+'sessions/week-6-day-2/playbook.html');assert.equal(await page.locator('.task-card .bmai-task-facts').count(),5);assert((await page.locator('#task-2 .bmai-task-facts').textContent()).includes('Task 1'));assert((await page.locator('#task-5 .bmai-task-facts').textContent()).includes('submission instructions'));assert(!(await page.locator('#task-1').textContent()).includes('shorten dialogue'));
 for(const width of [320,390,820,1440]){await page.setViewportSize({width,height:900});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:path.join(out,'ugc-'+width+'.png'),fullPage:true});results.screenshots.push('ugc-'+width+'.png');}
 // 200% zoom-equivalent width and focused controls remain usable, with no overflow.
 await page.setViewportSize({width:720,height:450});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));results.checks.push('Five distinct UGC handoffs and responsive expanded task layout');
 await context.close();
 const denied=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});await denied.addInitScript(()=>{const native=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key.startsWith('bmai-tasks:'))throw new DOMException('Storage unavailable','QuotaExceededError');return native.call(this,key,value);};});
 const storage=await denied.newPage();await storage.clock.install({time:new Date('2026-11-23T12:00:00+05:30')});await storage.goto(base+'playbook.html');assert((await storage.locator('.bmai-save-notice').textContent()).includes('could not save'));
 const box=storage.locator('#checklistSection [data-task-key]').first();await storage.locator('#checklistSection label').first().click();assert(await box.isChecked());assert((await storage.locator('.bmai-save-notice').textContent()).includes('could not save'));assert(!(await storage.locator('.bmai-save-notice').textContent()).includes('and saved'));
 await storage.locator('.bmai-progress-transfer summary').click();const download=storage.waitForEvent('download');await storage.locator('[data-export-progress]').click();const file=await download,backup=path.join(out,'denied-storage-backup.json');await file.saveAs(backup);const key=await box.getAttribute('data-task-key');assert.equal(JSON.parse(fs.readFileSync(backup,'utf8')).checkpoints['bmai-tasks:week-1-day-2'][key],true);await denied.close();results.checks.push('Denied storage shows a failure and exports the unsaved in-memory checkpoint');
 assert.equal(errors.length,0,errors.join('; '));fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.log(results.checks.length+' audit regression groups passed.');
 }finally{await browser.close();}})().catch(error=>{console.error(error);process.exit(1)});
