const fs=require('fs'),path=require('path'),assert=require('assert'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),base=process.env.BMAI_BASE_URL||'http://127.0.0.1:8771/',out=path.join(__dirname,'artifacts/final-review');fs.mkdirSync(out,{recursive:true});
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
const pages=require('../scripts/public-pages.cjs')();
const results={migration:[],prompts:[],localAssetFootprint:[],accessibleNames:[],screenshots:0};
(async()=>{const b=await chromium.launch({...(process.platform==='win32'?{channel:'chrome'}:{}),headless:true});
 for(const width of [390,1440]){const c=await b.newContext({viewport:{width,height:900},reducedMotion:'reduce'}),p=await c.newPage();await p.clock.install({time:new Date('2026-11-23T12:00:00+05:30')});
  for(const file of pages){const requested=new Set();const listener=r=>{if(r.url().startsWith(base))requested.add(new URL(r.url()).pathname.slice(1));};p.on('request',listener);await p.goto(base+file,{waitUntil:'networkidle'});
   if(['index.html','playbook.html'].includes(file)&&width===390){results.localAssetFootprint.push({file,viewport:width,bytes:[...requested].reduce((sum,rel)=>{try{return sum+fs.statSync(path.join(root,rel)).size}catch{return sum}},0)});}
   p.off('request',listener);const unnamed=await p.locator('input,textarea,select').evaluateAll(es=>es.filter(e=>e.type!=='hidden'&&!e.getAttribute('aria-label')&&!e.getAttribute('aria-labelledby')&&!e.labels?.length).map(e=>({tag:e.tagName,type:e.type,id:e.id})));assert.equal(unnamed.length,0,file+' unnamed fields');results.accessibleNames.push({file,width,unnamed:0});
   for(const slot of ['top','middle','end']){await p.evaluate(slot=>{const h=document.documentElement.scrollHeight;window.scrollTo({top:slot==='top'?0:slot==='end'?h:Math.max(0,(h-innerHeight)/2),behavior:'instant'});},slot);await p.waitForTimeout(180);await p.screenshot({path:path.join(out,file.replaceAll('/','-').replace('.html','')+'-'+width+'-'+slot+'.png')});results.screenshots++;}
   if(file==='sessions/week-4-day-1/playbook.html'){await p.locator('[data-library-quiz]').scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,'quiz-week4day1-'+width+'.png')});}
  }await c.close();
 }
 // A resource visit before a playbook must not erase an existing playbook's older saved state.
 const c=await b.newContext({viewport:{width:390,height:900}}),p=await c.newPage();await p.clock.install({time:new Date('2026-11-23T12:00:00+05:30')});await p.goto(base+'404.html');await p.evaluate(()=>{localStorage.clear();localStorage.setItem('bmai-progress:playbook.html',JSON.stringify(Array(19).fill(true)));localStorage.setItem('w2d1-session',JSON.stringify({0:true,1:true,2:true,3:true}));localStorage.setItem('w2d2',JSON.stringify(Array(40).fill(true)));});await p.goto(base+'index.html');await p.goto(base+'playbook.html');assert.equal(await p.locator('main input[type=checkbox]:checked').count(),19);assert.equal(await p.locator('#progressNumber').textContent(),'100%');results.migration.push('Playbook legacy ticks restored after resource visit');
 for(const file of ['sessions/week-2-day-1/index.html','sessions/week-2-day-2/index.html']){await p.goto(base+file);assert.equal(await p.locator('main input[type=checkbox]:checked').count(),await p.locator('main input[type=checkbox]').count());results.migration.push(file+' legacy ticks restored');}
 // Every full prompt matches the exact source text, including HTML-encoded characters.
 await p.goto(base+'index.html');const prompts=await p.locator('#resource-panel-prompts .studio-resource-card:has(pre)').evaluateAll(es=>es.map(e=>({text:e.querySelector('pre').textContent.trim(),source:e.querySelector('.studio-resource-source').href})));for(const prompt of prompts){await p.goto(prompt.source);const hash=new URL(prompt.source).hash;const text=await p.locator(hash).evaluate(target=>(target.matches('pre')?target:target.querySelector('pre'))?.textContent||'');assert.equal(prompt.text,text.trim(),prompt.source+' prompt differs');results.prompts.push({source:prompt.source,exact:true});}
 await c.close();await b.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.log('All '+results.screenshots+' viewport captures, input labels, legacy-state migrations and '+results.prompts.length+' source prompt comparisons passed.');
})().catch(e=>{fs.writeFileSync(path.join(out,'partial-results.json'),JSON.stringify(results,null,2));console.error(e);process.exit(1)});
