const fs=require('fs'),path=require('path'),assert=require('assert'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),base=process.env.BMAI_BASE_URL||'http://127.0.0.1:8771/',out=path.join(__dirname,'artifacts/fixes');fs.mkdirSync(out,{recursive:true});
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
const pages=require('../scripts/public-pages.cjs')();
const results={progress:[],avatars:[],resources:{},quizzes:[],narrow:[],errors:[],requests:[]};
(async()=>{const browser=await chromium.launch({...(process.platform==='win32'?{channel:'chrome'}:{}),headless:true}),context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce',acceptDownloads:true,permissions:['clipboard-read','clipboard-write']}),p=await context.newPage();await p.clock.install({time:new Date('2026-11-23T12:00:00+05:30')});p.on('pageerror',e=>results.errors.push(e.message));
 for(const file of pages){await p.goto(base+file,{waitUntil:'networkidle'});
  if(file!=='index.html'){const boxes=p.locator('main input[type=checkbox]'),total=await boxes.count();if(total){await boxes.evaluateAll(es=>es.forEach(e=>{e.checked=true;e.dispatchEvent(new Event('change',{bubbles:true}));}));await p.reload({waitUntil:'networkidle'});const checked=await p.locator('main input[type=checkbox]:checked').count();assert.equal(checked,total,file+' lost ticks');const counters=await p.locator('#progressNumber,.bmai-progress-value').allTextContents();assert(counters.every(v=>v.trim()==='100%'),file+' stale progress '+counters);results.progress.push({file,total,restored:checked,counters});}}
  const custom=p.locator('.studio-avatar[data-avatar-tip]').first();if(await custom.count()){await custom.click();assert(await custom.evaluate(el=>{const host=el.closest('.studio-guidance,.bmai-avatar-rail,.studio-companion')||el.parentElement;return host.querySelector('.studio-avatar-tip').textContent===el.dataset.avatarTip}),file+' incorrect tip');}
  const avatars=await p.locator('.studio-avatar').evaluateAll(es=>es.map(e=>e.dataset.avatarPose));const newPoses=await p.evaluate(()=>window.BMAI_AVATARS.poses);assert(avatars.every(pose=>newPoses.includes(pose)),file+' uses an unregistered pose');assert(new Set(avatars).size>=(file==='404.html'||file.endsWith('prompt-vault.html')?1:4),file+' needs more pose variety');results.avatars.push({file,count:avatars.length,poses:[...new Set(avatars)]});
  if(file.endsWith('playbook.html')&&await p.locator('[data-library-quiz]').count()){const answers=await p.evaluate(()=>window.BMAI_LESSON.quiz.map(q=>q.correct));for(let i=0;i<answers.length;i++){const group=p.locator('[data-library-quiz] fieldset').nth(i);await group.locator('input').nth(answers[i]).check();await group.locator('button').click();assert((await group.locator('p').textContent()).startsWith('Correct.'));}results.quizzes.push({file,questions:answers.length});}
 }
 await p.goto(base+'index.html',{waitUntil:'networkidle'});await p.locator('[data-resource-tab=checklists]').click();let group=p.locator('[data-resource-checklist="week-1-day-2"]');assert.equal(await group.locator('input:checked').count(),await group.locator('input').count());await group.locator('xpath=ancestor::details[1]').locator('summary').first().click();await group.locator('input').first().uncheck();await p.goto(base+'playbook.html',{waitUntil:'networkidle'});assert.equal(await p.locator('#checklist input:checked').count(),10);results.resources.sharedProgress=true;
 await p.goto(base+'index.html',{waitUntil:'networkidle'});assert.equal(await p.locator('.bmai-resume a').count(),0);assert((await p.locator('[data-current-action] span').innerText()).includes('RESUME'),'the primary hero action should resume the last lesson without adding a duplicate button');const headerActions=await p.locator('.bmai-global-header .nav-links>a').evaluateAll(links=>links.map(link=>({label:(link.textContent||link.getAttribute('aria-label')).trim(),home:link.classList.contains('bmai-header-home')})));assert(headerActions[0].home&&headerActions[1].label==='Sessions','Home must sit immediately before Sessions');assert(!/^0 of /.test(await p.locator('[data-home-progress-detail]').innerText()),'homepage progress should reflect saved playbook checks');await p.locator('#bmai-site-search').fill('camera movement');assert(await p.locator('[data-site-search-results] a').count()>0,'studio search should find matching content');results.resources.studioSearch=true;await p.locator('[data-resource-tab=prompts]').click();await p.locator('input[aria-label="Find a resource"]').fill('macro');await p.locator('select[aria-label="Filter resources by session"]').selectOption('week-4-day-2');const cards=p.locator('#resource-panel-prompts .studio-resource-card:not([hidden])');assert(await cards.count()>0);results.resources.filtered=await cards.count();await cards.first().locator('summary').first().click();const detail=cards.first();const expected=await detail.locator('pre').textContent();await detail.locator('[data-copy-prompt]').click();assert.equal(await p.evaluate(()=>navigator.clipboard.readText()),expected);results.resources.copyExact=true;await p.screenshot({path:path.join(out,'resource-search-mobile.png'),fullPage:true});
 await p.setViewportSize({width:320,height:844});for(const file of pages){await p.goto(base+file,{waitUntil:'networkidle'});const overflow=await p.evaluate(()=>Math.max(document.documentElement.scrollWidth,document.body.scrollWidth)-innerWidth);assert(overflow<=1,file+' overflow at 320');results.narrow.push({file,width:320,overflow});}
 const locked=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'}),lp=await locked.newPage();await lp.clock.install({time:new Date('2026-10-08T12:00:00+05:30')});await lp.goto(base+'sessions/week-4-day-2/playbook.html',{waitUntil:'networkidle'});assert.equal(await lp.locator('.bmai-lock-avatars .studio-avatar').count(),1);assert.equal((await lp.locator('.bmai-lock-home').innerText()).trim(),'Back to Home');await lp.screenshot({path:path.join(out,'locked-mobile.png'),fullPage:true});results.resources.lockAvatars=1;await locked.close();
 await p.setViewportSize({width:1440,height:960});await p.clock.setFixedTime(new Date('2026-11-23T12:00:00+05:30'));await p.goto(base+'index.html',{waitUntil:'networkidle'});const finalWeek=await p.evaluate(()=>window.BMAI_SESSIONS.filter(s=>s.session).at(-1).week);assert((await p.locator('.bmai-studio-card h2').textContent()).includes(finalWeek),'the current lesson should track the latest authored session after the cohort ends');results.resources.afterCohort=true;
 assert.equal(results.errors.length,0,results.errors.join(';'));await browser.close();fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));console.log('Saved progress, shared resource checks, search, exact copy, quizzes, 320px layouts, avatar tips and locks passed.');
})().catch(e=>{fs.writeFileSync(path.join(out,'partial-results.json'),JSON.stringify(results,null,2));console.error(e);process.exit(1)});
